package task;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;
/* Lambda expression has two rules:
1. lambda expression need an interface
2. Interface has to same signature with lambda expression
 */

public class OrangeTest {
    public static void main(String[] args) {
        List <Orange> inventory = new ArrayList<>();
        //Directly calling a constructor of the Orange class.
        inventory.add(new Orange(200, Color.GREEN));
        //Using the Builder pattern, usually generated by Lombok (@Builder) or implemented manually.
        inventory.add(Orange.builder().weight(150).color(Color.GREEN).build());
        inventory.add(Orange.builder().weight(250).color(Color.RED).build());
        inventory.add(Orange.builder().weight(350).color(Color.RED).build());
        inventory.add(Orange.builder().weight(450).color(Color.GREEN).build());

        //first way
        //prettyPrintOrange(inventory, Orange::toString);
        //second way
//        OrangeFormatter simpleFormatter = orange-> "An orange of " + orange.getWeight() + "g";
//        prettyPrintOrange(inventory, simpleFormatter);
//
//        OrangeFormatter fancyFormatter = orange-> {
//            String category = orange.getWeight()>200 ? "Heavy" : "Light";
//            return "A " + category + " " + orange.getColor() + " orange";
//        };
//        prettyPrintOrange(inventory, fancyFormatter);

        prettyPrintOrange (inventory, o ->
        {
            System.out.println("A " + (o.getWeight() > 200 ? "Heavy" : "Light")
                    + " " + o.getColor() + " orange");
            return o;
        });
    }
//    private static void prettyPrintOrange (List<Orange> inventory, OrangeFormatter formatter){
//        for (Orange orange : inventory){
//            String output = formatter.accept(orange);
//            System.out.println(output);
//        }
//    }


    //Using functional interface for lambda expression
    private static void prettyPrintOrange (List<Orange> inventory, Function<Orange, Orange> format){
        for (Orange orange : inventory) {
             Orange obj = format.apply(orange);
              System.out.println(obj);
            }
    }

}
